# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcd929c7cac49b83dd71a2a60511aa4dff75ab01a240a99b3c2978ebc3b91184b2a2562e8b3840667d628ea0d854a7d901f0eaf7fc534f1fa3e850c71358e5db

test:
  secret_key_base: 5ebbbf04f1225780f17a8439f3294e79d6a6131d4a800f85453afc75ebe15131f98782eb6981ba0df3fb4920a8b810720d5929a860d289dab4f86af934326c93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
